# Site settings
title: "Archived Roger Stringer"
email: roger.stringer@me.com
description: > # this means to ignore newlines until "baseurl:"
  I’m Roger Stringer, and this is the archive, where older posts go to live.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://archived.rogerstringer.com" # the base hostname & protocol for your site
twitter_username: freekrai
github_username:  freekrai

# Build settings
encoding: utf-8
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "footnotes"]
highlighter: rouge
paginate: 20
permalink: pretty


gems:
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
